name: Build NutriAI Pro for Appetize

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Download source code
      uses: actions/checkout@v4

    - name: Install XcodeGen
      run: brew install xcodegen

    - name: Generate Xcode Project
      run: xcodegen generate

    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Build for Simulator
      run: |
        xcodebuild -project NutriAIPro.xcodeproj -scheme NutriAIPro -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=latest' clean build CONFIGURATION_BUILD_DIR="./build" CODE_SIGNING_ALLOWED="NO" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_IDENTITY=""

    - name: Zip the .app for Appetize
      run: |
        cd build
        zip -r NutriAIPro-Simulator.zip NutriAIPro.app

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NutriAIPro-Simulator-Build
        path: build/NutriAIPro-Simulator.zip
